[package]
name = "picomenu"
version = "0.1.0"
edition = "2021"

[[test]]
name = "menu"
src = "menu.rs"

[dependencies]
defmt = "0.3.8"
ufmt = "0.2.0"

[dev-dependencies]
tokio = { version = "1.41.1", features = ["rt", "macros"] }
