[package]
name = "picomenu"
version = "0.1.1"
edition = "2021"

[[test]]
name = "menu"
src = "menu.rs"

[dependencies]
defmt = "1.0"
ufmt = "0.2"

[dev-dependencies]
tokio = { version = "1.45", features = ["rt", "macros"] }
