[package]
name = "picomenu"
version = "0.1.1"
edition = "2024"

[[test]]
name = "menu"

[dependencies]
defmt = "1.0"
ufmt = "0.2"

[dev-dependencies]
tokio = { version = "1.45", features = ["rt", "macros"] }
